### 读取 角色职业数据-7，使用apply方法将已知橘色与未知角色的特征值归一化。

In [9]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# 导入数据
file = r'C:\Users\YcAllenEffy\Desktop\fire_emblem_7.xlsx'
df_src = pd.read_excel(file, sheet_name=0)      # 已知数据
df_ans = pd.read_excel(file, sheet_name=1)  # 未知数据

In [2]:
df_src

       角色   职业  HP  力量  魔力  技巧  速度  幸运  防守  魔防  行动点     修正
0   艾黛尔贾特   剑客  20   7   3   6   6   4   5   2    4  10180
1    帝弥托利   士兵  20   8   3   6   6   4   5   2    4  10140
2     库罗德   战士  20   8   3   6   6   4   5   2    4    200
3     修伯特  修道士  20   4   8   6   6   4   3   4    4  10240
4   菲尔迪南特   领主  25   9   6  10  10   8   6   3    5  10260
..    ...  ...  ..  ..  ..  ..  ..  ..  ..  ..  ...    ...
61     尼诺   盗贼  25   9   6  11  11   8   6   2    5    155
62    加法尔  重骑士  30   9   6   7   4   8  12   1    4  10200
63    瓦依达   佣兵  25   9   6  10  10   8   6   2    5  10110
64    莱那特   盗贼  25   9   6  11  11   8   6   2    5    155
65    阿特斯   佣兵  25   9   6  10  10   8   6   2    5  10110

[66 rows x 12 columns]

In [7]:
# 已知数据的归一化
df_src.iloc[:,2:].apply(lambda x:(x-x.min())/(x.max()-x.min()))

     HP   力量   魔力   技巧        速度   幸运        防守        魔防       行动点        修正
0   0.0  0.6  0.0  0.0  0.285714  0.0  0.222222  0.333333  0.000000  0.988172
1   0.0  0.8  0.0  0.0  0.285714  0.0  0.222222  0.333333  0.000000  0.984229
2   0.0  0.8  0.0  0.0  0.285714  0.0  0.222222  0.333333  0.000000  0.004436
3   0.0  0.0  1.0  0.0  0.285714  0.0  0.000000  1.000000  0.000000  0.994086
4   0.5  1.0  0.6  0.8  0.857143  1.0  0.333333  0.666667  0.333333  0.996057
..  ...  ...  ...  ...       ...  ...       ...       ...       ...       ...
61  0.5  1.0  0.6  1.0  1.000000  1.0  0.333333  0.333333  0.333333  0.000000
62  1.0  1.0  0.6  0.2  0.000000  1.0  1.000000  0.000000  0.000000  0.990143
63  0.5  1.0  0.6  0.8  0.857143  1.0  0.333333  0.333333  0.333333  0.981272
64  0.5  1.0  0.6  1.0  1.000000  1.0  0.333333  0.333333  0.333333  0.000000
65  0.5  1.0  0.6  0.8  0.857143  1.0  0.333333  0.333333  0.333333  0.981272

[66 rows x 10 columns]

In [15]:
# 未知数据的归一化
df_src.append(df_ans).iloc[:,2:].apply(lambda x:(x-x.min())/(x.max()-x.min())).iloc[-1:,:]

    HP   力量   魔力   技巧        速度   幸运        防守   魔防       行动点        修正
0  0.5  1.0  0.4  0.8  0.857143  1.0  0.222222  1.0  0.333333  0.007393

In [17]:
# 标准答案
import pandas as pd

# 导入数据
file =r'C:\Users\YcAllenEffy\Desktop\fire_emblem_7.xlsx'
df_src = pd.read_excel(file, sheet_name=0)      # 已知数据
df_unknown = pd.read_excel(file, sheet_name=1)  # 未知数据

df_a = df_src.append(df_unknown).iloc[:, 2:12]  # 合并数据集
df_res = df_a.apply(lambda col: (col-col.min())/(col.max()-col.min()))
df_res

     HP        力量   魔力   技巧        速度   幸运        防守    魔防       行动点        修正
0   0.0  0.500000  0.0  0.0  0.285714  0.0  0.222222  0.25  0.000000  0.988172
1   0.0  0.666667  0.0  0.0  0.285714  0.0  0.222222  0.25  0.000000  0.984229
2   0.0  0.666667  0.0  0.0  0.285714  0.0  0.222222  0.25  0.000000  0.004436
3   0.0  0.000000  1.0  0.0  0.285714  0.0  0.000000  0.75  0.000000  0.994086
4   0.5  0.833333  0.6  0.8  0.857143  0.8  0.333333  0.50  0.333333  0.996057
..  ...       ...  ...  ...       ...  ...       ...   ...       ...       ...
62  1.0  0.833333  0.6  0.2  0.000000  0.8  1.000000  0.00  0.000000  0.990143
63  0.5  0.833333  0.6  0.8  0.857143  0.8  0.333333  0.25  0.333333  0.981272
64  0.5  0.833333  0.6  1.0  1.000000  0.8  0.333333  0.25  0.333333  0.000000
65  0.5  0.833333  0.6  0.8  0.857143  0.8  0.333333  0.25  0.333333  0.981272
0   0.5  1.000000  0.4  0.8  0.857143  1.0  0.222222  1.00  0.333333  0.007393

[67 rows x 10 columns]

###  读取 角色职业数据-7，使用 MinMaxScaler 进行数据规范化，并通过交叉验证推测未知角色的职业。

In [44]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split ,GridSearchCV
from sklearn.metrics import accuracy_score

# 导入数据
file = r'C:\Users\YcAllenEffy\Desktop\fire_emblem_7.xlsx'
df_src = pd.read_excel(file, sheet_name=0)      # 已知数据
df_ans = pd.read_excel(file, sheet_name=1)  # 未知数据

In [47]:
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()
x=mms.fit_transform(df_src.iloc[:,2:])
y=df_src['职业']

knn=KNeighborsClassifier()
gscv=GridSearchCV(knn,{'n_neighbors':range(1,10,2)},cv=3)

gscv.fit(x,y)
pd.DataFrame(gscv.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000667,0.000472,0.000667,4.717642e-04,1,{'n_neighbors': 1},1.000000,1.000000,1.000000,1.000000,0.000000,1
1,0.000000,0.000000,0.001001,6.726175e-05,3,{'n_neighbors': 3},1.000000,1.000000,1.000000,1.000000,0.000000,1
2,0.000334,0.000472,0.001001,1.123916e-07,5,{'n_neighbors': 5},0.909091,0.954545,0.954545,0.939394,0.021427,3
3,0.000667,0.000472,0.000334,4.718199e-04,7,{'n_neighbors': 7},0.863636,0.863636,0.863636,0.863636,0.000000,4
4,0.000334,0.000472,0.000667,4.718200e-04,9,{'n_neighbors': 9},0.681818,0.818182,0.818182,0.772727,0.064282,5

In [41]:
mms.fit_transform(df_src.append(df_ans).iloc[:,2:])[-1]

array([0.5       , 1.        , 0.4       , 0.8       , 0.85714286,
       1.        , 0.22222222, 1.        , 0.33333333, 0.0073928 ])

In [40]:
mms.fit_transform(df_src.append(df_ans).iloc[:,2:])[-1:,:]

array([[0.5       , 1.        , 0.4       , 0.8       , 0.85714286,
        1.        , 0.22222222, 1.        , 0.33333333, 0.0073928 ]])

In [42]:
k=gscv.best_params_
x=mms.fit_transform(df_src.iloc[:,2:])
y=df_src['职业']
knn=KNeighborsClassifier(n_neighbors=k['n_neighbors'])
model=knn.fit(x,y)
model.predict(mms.fit_transform(df_src.append(df_ans).iloc[:,2:])[-1:,:])

array(['盗贼'], dtype=object)

In [49]:
# 标准答案
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import MinMaxScaler

# 导入数据
file =r'C:\Users\YcAllenEffy\Desktop\fire_emblem_7.xlsx'
df_src = pd.read_excel(file, sheet_name=0)      # 已知数据
df_unknown = pd.read_excel(file, sheet_name=1)  # 未知数据
# 数据规范化
mms = MinMaxScaler()
x = mms.fit_transform( df_src.iloc[:,2:12] )
y = df_src['职业']
# 交叉验证得到k
knn = KNeighborsClassifier()
gscv = GridSearchCV( knn, {'n_neighbors':range(1,10,2)}, cv=3, 
                    return_train_score=True )
gscv.fit(x, y)
pd.DataFrame(gscv.cv_results_)
k = gscv.best_params_['n_neighbors']
# 重新训练模型，预测未知角色
knn = KNeighborsClassifier( n_neighbors=k )
model = knn.fit(x, y)
x_unknown = mms.fit_transform(df_src.append(df_unknown).iloc[:, 2:12] )[-1:, :]
res = model.predict( x_unknown )[0]
print('未知角色的职业是：', res,'k值为',k)

未知角色的职业是： 盗贼 k值为 1