In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 10)
sh=pd.read_excel(r'C:\Users\YcAllenEffy\Desktop\house2.xlsx',sheet_name=0,index_col=0)
sh.info()

<class 'pandas.core.frame.DataFrame'>
Index: 97 entries, 逸成东01 to 龙博苑01
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   所在社区编号  97 non-null     int64
 1   交易时间    97 non-null     datetime64[ns]
 2   挂牌天数    97 non-null     int64
 3   关注人数    97 non-null     int64
 4   总价      97 non-null     float64
 5   平米均价    97 non-null     int64
 6   面积      97 non-null     float64
 7   卧室      97 non-null     int64
 8   客厅      97 non-null     int64
 9   厨房      97 non-null     int64
 10  浴室      97 non-null     int64
 11  楼层信息    97 non-null     object
 12  建成时间    97 non-null     int64
 13  链家网址    97 non-null     object
dtypes: datetime64[ns](1), float64(2), int64(9), object(2)
memory usage: 11.4+ KB

In [4]:
sh.describe()

,所在社区编号,挂牌天数,关注人数,总价,平米均价,面积,卧室,客厅,厨房,浴室,建成时间
count,9.700000e+01,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.0,97.000000,97.000000
mean,1.111029e+12,62.072165,57.546392,477.705155,58801.288660,83.326598,1.989691,1.154639,1.0,1.206186,2000.628866
std,5.356475e+06,62.721150,66.369393,272.694628,23622.173974,33.730578,0.770482,0.416838,0.0,0.406667,9.014248
min,1.111027e+12,2.000000,0.000000,168.000000,20128.000000,32.710000,1.000000,0.000000,1.0,1.000000,1973.000000
25%,1.111027e+12,14.000000,15.000000,325.500000,41931.000000,56.500000,1.000000,1.000000,1.0,1.000000,1996.000000
50%,1.111027e+12,39.000000,38.000000,387.000000,52216.000000,76.410000,2.000000,1.000000,1.0,1.000000,2003.000000
75%,1.111027e+12,86.000000,82.000000,568.000000,69474.000000,101.580000,2.000000,1.000000,1.0,1.000000,2008.000000
max,1.111053e+12,259.000000,370.000000,1655.000000,142120.000000,185.530000,4.000000,2.000000,1.0,2.000000,2014.000000

In [5]:
sh

,所在社区编号,交易时间,挂牌天数,关注人数,总价,平米均价,面积,卧室,客厅,厨房,浴室,楼层信息,建成时间,链家网址
id,,,,,,,,,,,,,,
逸成东01,1111027381533,2018-01-03,2,0,607.0,80729,75.19,2,1,1,1,中 22,2003,https://bj.lianjia.com/chengjiao/101102451242....
天通苑05,1111027380051,2018-01-03,2,0,372.0,41822,88.95,2,1,1,1,高 6,2001,https://bj.lianjia.com/chengjiao/101102452309....
汽南小01,1111027378900,2018-01-03,4,0,509.0,121191,42.00,1,1,1,1,顶 6,1985,https://bj.lianjia.com/chengjiao/101102446043....
门头沟01,1111052073923,2018-01-03,4,0,173.0,37495,46.14,1,1,1,1,顶 6,1990,https://bj.lianjia.com/chengjiao/101102446345....
新街口01,1111027380943,2018-01-03,4,0,1120.0,102970,108.77,3,1,1,2,中 6,2005,https://bj.lianjia.com/chengjiao/101102447671....
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
模式口01,1111027378400,2018-01-03,201,2,260.0,47247,55.03,2,1,1,1,中 6,1986,https://bj.lianjia.com/chengjiao/101101704540....
绿地新01,1111052857099,2018-01-03,208,38,305.0,34731,87.82,2,1,1,1,高 14,2012,https://bj.lianjia.com/chengjiao/101101685048....
兴隆家01,1111027381021,2018-01-03,229,100,515.0,49306,104.45,3,1,1,1,中 24,2001,https://bj.lianjia.com/chengjiao/101101601669....
融科香01,1111027379032,2018-01-03,231,9,507.0,36071,140.56,3,2,1,2,中 6,2009,https://bj.lianjia.com/chengjiao/101101594408....
龙博苑01,1111027377718,2018-01-03,259,226,380.0,47560,79.90,2,1,1,1,中 6,2004,https://bj.lianjia.com/chengjiao/101101492812....

In [7]:
sh.drop('交易时间',axis=1)

,所在社区编号,挂牌天数,关注人数,总价,平米均价,面积,卧室,客厅,厨房,浴室,楼层信息,建成时间,链家网址
id,,,,,,,,,,,,,
逸成东01,1111027381533,2,0,607.0,80729,75.19,2,1,1,1,中 22,2003,https://bj.lianjia.com/chengjiao/101102451242....
天通苑05,1111027380051,2,0,372.0,41822,88.95,2,1,1,1,高 6,2001,https://bj.lianjia.com/chengjiao/101102452309....
汽南小01,1111027378900,4,0,509.0,121191,42.00,1,1,1,1,顶 6,1985,https://bj.lianjia.com/chengjiao/101102446043....
门头沟01,1111052073923,4,0,173.0,37495,46.14,1,1,1,1,顶 6,1990,https://bj.lianjia.com/chengjiao/101102446345....
新街口01,1111027380943,4,0,1120.0,102970,108.77,3,1,1,2,中 6,2005,https://bj.lianjia.com/chengjiao/101102447671....
...,...,...,...,...,...,...,...,...,...,...,...,...,...
模式口01,1111027378400,201,2,260.0,47247,55.03,2,1,1,1,中 6,1986,https://bj.lianjia.com/chengjiao/101101704540....
绿地新01,1111052857099,208,38,305.0,34731,87.82,2,1,1,1,高 14,2012,https://bj.lianjia.com/chengjiao/101101685048....
兴隆家01,1111027381021,229,100,515.0,49306,104.45,3,1,1,1,中 24,2001,https://bj.lianjia.com/chengjiao/101101601669....
融科香01,1111027379032,231,9,507.0,36071,140.56,3,2,1,2,中 6,2009,https://bj.lianjia.com/chengjiao/101101594408....
龙博苑01,1111027377718,259,226,380.0,47560,79.90,2,1,1,1,中 6,2004,https://bj.lianjia.com/chengjiao/101101492812....

In [12]:
sh.drop(sh.columns[2],axis=1)

,所在社区编号,交易时间,关注人数,总价,平米均价,面积,卧室,客厅,厨房,浴室,楼层信息,建成时间,链家网址
id,,,,,,,,,,,,,
逸成东01,1111027381533,2018-01-03,0,607.0,80729,75.19,2,1,1,1,中 22,2003,https://bj.lianjia.com/chengjiao/101102451242....
天通苑05,1111027380051,2018-01-03,0,372.0,41822,88.95,2,1,1,1,高 6,2001,https://bj.lianjia.com/chengjiao/101102452309....
汽南小01,1111027378900,2018-01-03,0,509.0,121191,42.00,1,1,1,1,顶 6,1985,https://bj.lianjia.com/chengjiao/101102446043....
门头沟01,1111052073923,2018-01-03,0,173.0,37495,46.14,1,1,1,1,顶 6,1990,https://bj.lianjia.com/chengjiao/101102446345....
新街口01,1111027380943,2018-01-03,0,1120.0,102970,108.77,3,1,1,2,中 6,2005,https://bj.lianjia.com/chengjiao/101102447671....
...,...,...,...,...,...,...,...,...,...,...,...,...,...
模式口01,1111027378400,2018-01-03,2,260.0,47247,55.03,2,1,1,1,中 6,1986,https://bj.lianjia.com/chengjiao/101101704540....
绿地新01,1111052857099,2018-01-03,38,305.0,34731,87.82,2,1,1,1,高 14,2012,https://bj.lianjia.com/chengjiao/101101685048....
兴隆家01,1111027381021,2018-01-03,100,515.0,49306,104.45,3,1,1,1,中 24,2001,https://bj.lianjia.com/chengjiao/101101601669....
融科香01,1111027379032,2018-01-03,9,507.0,36071,140.56,3,2,1,2,中 6,2009,https://bj.lianjia.com/chengjiao/101101594408....
龙博苑01,1111027377718,2018-01-03,226,380.0,47560,79.90,2,1,1,1,中 6,2004,https://bj.lianjia.com/chengjiao/101101492812....

In [11]:
sh.columns

Index(['所在社区编号', '交易时间', '挂牌天数', '关注人数', '总价', '平米均价', '面积', '卧室', '客厅', '厨房',
       '浴室', '楼层信息', '建成时间', '链家网址'],
      dtype='object')

In [13]:
sh.loc['全民有房']=520
sh

,所在社区编号,交易时间,挂牌天数,关注人数,总价,平米均价,面积,卧室,客厅,厨房,浴室,楼层信息,建成时间,链家网址
id,,,,,,,,,,,,,,
逸成东01,1111027381533,2018-01-03 00:00:00,2,0,607.0,80729,75.19,2,1,1,1,中 22,2003,https://bj.lianjia.com/chengjiao/101102451242....
天通苑05,1111027380051,2018-01-03 00:00:00,2,0,372.0,41822,88.95,2,1,1,1,高 6,2001,https://bj.lianjia.com/chengjiao/101102452309....
汽南小01,1111027378900,2018-01-03 00:00:00,4,0,509.0,121191,42.00,1,1,1,1,顶 6,1985,https://bj.lianjia.com/chengjiao/101102446043....
门头沟01,1111052073923,2018-01-03 00:00:00,4,0,173.0,37495,46.14,1,1,1,1,顶 6,1990,https://bj.lianjia.com/chengjiao/101102446345....
新街口01,1111027380943,2018-01-03 00:00:00,4,0,1120.0,102970,108.77,3,1,1,2,中 6,2005,https://bj.lianjia.com/chengjiao/101102447671....
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
绿地新01,1111052857099,2018-01-03 00:00:00,208,38,305.0,34731,87.82,2,1,1,1,高 14,2012,https://bj.lianjia.com/chengjiao/101101685048....
兴隆家01,1111027381021,2018-01-03 00:00:00,229,100,515.0,49306,104.45,3,1,1,1,中 24,2001,https://bj.lianjia.com/chengjiao/101101601669....
融科香01,1111027379032,2018-01-03 00:00:00,231,9,507.0,36071,140.56,3,2,1,2,中 6,2009,https://bj.lianjia.com/chengjiao/101101594408....
龙博苑01,1111027377718,2018-01-03 00:00:00,259,226,380.0,47560,79.90,2,1,1,1,中 6,2004,https://bj.lianjia.com/chengjiao/101101492812....
全民有房,520,520,520,520,520.0,520,520.00,520,520,520,520,520,520,520

In [14]:
sh.shape

(98, 14)

In [7]:
df_db=sh.describe()

In [22]:
df_db.loc[['mean','std']]

,所在社区编号,挂牌天数,关注人数,总价,平米均价,面积,卧室,客厅,厨房,浴室,建成时间
mean,1.111029e+12,62.072165,57.546392,477.705155,58801.288660,83.326598,1.989691,1.154639,1.0,1.206186,2000.628866
std,5.356475e+06,62.721150,66.369393,272.694628,23622.173974,33.730578,0.770482,0.416838,0.0,0.406667,9.014248

In [24]:
sh.tail(3)

,所在社区编号,交易时间,挂牌天数,关注人数,总价,平米均价,面积,卧室,客厅,厨房,浴室,楼层信息,建成时间,链家网址
id,,,,,,,,,,,,,,
兴隆家01,1111027381021,2018-01-03,229,100,515.0,49306,104.45,3,1,1,1,中 24,2001,https://bj.lianjia.com/chengjiao/101101601669....
融科香01,1111027379032,2018-01-03,231,9,507.0,36071,140.56,3,2,1,2,中 6,2009,https://bj.lianjia.com/chengjiao/101101594408....
龙博苑01,1111027377718,2018-01-03,259,226,380.0,47560,79.90,2,1,1,1,中 6,2004,https://bj.lianjia.com/chengjiao/101101492812....

In [33]:
pd.set_option('display.precision',1)
sh

              所在社区编号       交易时间  挂牌天数  关注人数      总价    平米均价     面积  卧室  客厅  厨房  浴室  楼层信息  建成时间                                               链家网址
id
逸成东01  1111027381533 2018-01-03     2     0   607.0   80729   75.2   2   1   1   1  中 22  2003  https://bj.lianjia.com/chengjiao/101102451242....
天通苑05  1111027380051 2018-01-03     2     0   372.0   41822   89.0   2   1   1   1   高 6  2001  https://bj.lianjia.com/chengjiao/101102452309....
汽南小01  1111027378900 2018-01-03     4     0   509.0  121191   42.0   1   1   1   1   顶 6  1985  https://bj.lianjia.com/chengjiao/101102446043....
门头沟01  1111052073923 2018-01-03     4     0   173.0   37495   46.1   1   1   1   1   顶 6  1990  https://bj.lianjia.com/chengjiao/101102446345....
新街口01  1111027380943 2018-01-03     4     0  1120.0  102970  108.8   3   1   1   2   中 6  2005  https://bj.lianjia.com/chengjiao/101102447671....
...              ...        ...   ...   ...     ...     ...    ...  ..  ..  ..  ..   ...   ...                                                ...
模式口01  1111027378400 2018-01-03   201     2   260.0   47247   55.0   2   1   1   1   中 6  1986  https://bj.lianjia.com/chengjiao/101101704540....
绿地新01  1111052857099 2018-01-03   208    38   305.0   34731   87.8   2   1   1   1  高 14  2012  https://bj.lianjia.com/chengjiao/101101685048....
兴隆家01  1111027381021 2018-01-03   229   100   515.0   49306  104.5   3   1   1   1  中 24  2001  https://bj.lianjia.com/chengjiao/101101601669....
融科香01  1111027379032 2018-01-03   231     9   507.0   36071  140.6   3   2   1   2   中 6  2009  https://bj.lianjia.com/chengjiao/101101594408....
龙博苑01  1111027377718 2018-01-03   259   226   380.0   47560   79.9   2   1   1   1   中 6  2004  https://bj.lianjia.com/chengjiao/101101492812....

[97 rows x 14 columns]

In [39]:
sh.drop('链家网址',axis=1)

              所在社区编号       交易时间  挂牌天数  关注人数      总价    平米均价     面积  卧室  客厅  厨房  浴室  楼层信息  建成时间
id
逸成东01  1111027381533 2018-01-03     2     0   607.0   80729   75.2   2   1   1   1  中 22  2003
天通苑05  1111027380051 2018-01-03     2     0   372.0   41822   89.0   2   1   1   1   高 6  2001
汽南小01  1111027378900 2018-01-03     4     0   509.0  121191   42.0   1   1   1   1   顶 6  1985
门头沟01  1111052073923 2018-01-03     4     0   173.0   37495   46.1   1   1   1   1   顶 6  1990
新街口01  1111027380943 2018-01-03     4     0  1120.0  102970  108.8   3   1   1   2   中 6  2005
...              ...        ...   ...   ...     ...     ...    ...  ..  ..  ..  ..   ...   ...
模式口01  1111027378400 2018-01-03   201     2   260.0   47247   55.0   2   1   1   1   中 6  1986
绿地新01  1111052857099 2018-01-03   208    38   305.0   34731   87.8   2   1   1   1  高 14  2012
兴隆家01  1111027381021 2018-01-03   229   100   515.0   49306  104.5   3   1   1   1  中 24  2001
融科香01  1111027379032 2018-01-03   231     9   507.0   36071  140.6   3   2   1   2   中 6  2009
龙博苑01  1111027377718 2018-01-03   259   226   380.0   47560   79.9   2   1   1   1   中 6  2004

[97 rows x 13 columns]

In [40]:
sh.drop(['逸成东01', '汽南小01', '门头沟01'])

              所在社区编号       交易时间  挂牌天数  关注人数      总价    平米均价     面积  卧室  客厅  厨房  浴室  楼层信息  建成时间                                               链家网址
id
天通苑05  1111027380051 2018-01-03     2     0   372.0   41822   89.0   2   1   1   1   高 6  2001  https://bj.lianjia.com/chengjiao/101102452309....
新街口01  1111027380943 2018-01-03     4     0  1120.0  102970  108.8   3   1   1   2   中 6  2005  https://bj.lianjia.com/chengjiao/101102447671....
新华联01  1111027380847 2018-01-03     5     1   405.0   42718   94.8   2   2   1   2   低 6  2004  https://bj.lianjia.com/chengjiao/101102443459....
瑞祥里01  1111027379066 2018-01-03     5     0   277.0   41699   66.4   1   1   1   1   中 9  2006  https://bj.lianjia.com/chengjiao/101102445248....
北街家02  1111027379515 2018-01-03     6    23   354.5   45432   78.0   3   1   1   1  高 18  2009  https://bj.lianjia.com/chengjiao/101102441034....
...              ...        ...   ...   ...     ...     ...    ...  ..  ..  ..  ..   ...   ...                                                ...
模式口01  1111027378400 2018-01-03   201     2   260.0   47247   55.0   2   1   1   1   中 6  1986  https://bj.lianjia.com/chengjiao/101101704540....
绿地新01  1111052857099 2018-01-03   208    38   305.0   34731   87.8   2   1   1   1  高 14  2012  https://bj.lianjia.com/chengjiao/101101685048....
兴隆家01  1111027381021 2018-01-03   229   100   515.0   49306  104.5   3   1   1   1  中 24  2001  https://bj.lianjia.com/chengjiao/101101601669....
融科香01  1111027379032 2018-01-03   231     9   507.0   36071  140.6   3   2   1   2   中 6  2009  https://bj.lianjia.com/chengjiao/101101594408....
龙博苑01  1111027377718 2018-01-03   259   226   380.0   47560   79.9   2   1   1   1   中 6  2004  https://bj.lianjia.com/chengjiao/101101492812....

[94 rows x 14 columns]

In [41]:
sh.drop(['平米均价', '楼层信息', '链家网址'],axis=1)

              所在社区编号       交易时间  挂牌天数  关注人数      总价     面积  卧室  客厅  厨房  浴室  建成时间
id
逸成东01  1111027381533 2018-01-03     2     0   607.0   75.2   2   1   1   1  2003
天通苑05  1111027380051 2018-01-03     2     0   372.0   89.0   2   1   1   1  2001
汽南小01  1111027378900 2018-01-03     4     0   509.0   42.0   1   1   1   1  1985
门头沟01  1111052073923 2018-01-03     4     0   173.0   46.1   1   1   1   1  1990
新街口01  1111027380943 2018-01-03     4     0  1120.0  108.8   3   1   1   2  2005
...              ...        ...   ...   ...     ...    ...  ..  ..  ..  ..   ...
模式口01  1111027378400 2018-01-03   201     2   260.0   55.0   2   1   1   1  1986
绿地新01  1111052857099 2018-01-03   208    38   305.0   87.8   2   1   1   1  2012
兴隆家01  1111027381021 2018-01-03   229   100   515.0  104.5   3   1   1   1  2001
融科香01  1111027379032 2018-01-03   231     9   507.0  140.6   3   2   1   2  2009
龙博苑01  1111027377718 2018-01-03   259   226   380.0   79.9   2   1   1   1  2004

[97 rows x 11 columns]

In [48]:
sh.drop(sh.iloc[1:5].index)

              所在社区编号       交易时间  挂牌天数  关注人数     总价   平米均价     面积  卧室  客厅  厨房  浴室  楼层信息  建成时间                                               链家网址
id
逸成东01  1111027381533 2018-01-03     2     0  607.0  80729   75.2   2   1   1   1  中 22  2003  https://bj.lianjia.com/chengjiao/101102451242....
新华联01  1111027380847 2018-01-03     5     1  405.0  42718   94.8   2   2   1   2   低 6  2004  https://bj.lianjia.com/chengjiao/101102443459....
瑞祥里01  1111027379066 2018-01-03     5     0  277.0  41699   66.4   1   1   1   1   中 9  2006  https://bj.lianjia.com/chengjiao/101102445248....
北街家02  1111027379515 2018-01-03     6    23  354.5  45432   78.0   3   1   1   1  高 18  2009  https://bj.lianjia.com/chengjiao/101102441034....
华芳园01  1111027374970 2018-01-03     6    23  305.0  50547   60.3   1   1   1   1  高 18  1999  https://bj.lianjia.com/chengjiao/101102441114....
...              ...        ...   ...   ...    ...    ...    ...  ..  ..  ..  ..   ...   ...                                                ...
模式口01  1111027378400 2018-01-03   201     2  260.0  47247   55.0   2   1   1   1   中 6  1986  https://bj.lianjia.com/chengjiao/101101704540....
绿地新01  1111052857099 2018-01-03   208    38  305.0  34731   87.8   2   1   1   1  高 14  2012  https://bj.lianjia.com/chengjiao/101101685048....
兴隆家01  1111027381021 2018-01-03   229   100  515.0  49306  104.5   3   1   1   1  中 24  2001  https://bj.lianjia.com/chengjiao/101101601669....
融科香01  1111027379032 2018-01-03   231     9  507.0  36071  140.6   3   2   1   2   中 6  2009  https://bj.lianjia.com/chengjiao/101101594408....
龙博苑01  1111027377718 2018-01-03   259   226  380.0  47560   79.9   2   1   1   1   中 6  2004  https://bj.lianjia.com/chengjiao/101101492812....

[93 rows x 14 columns]

In [55]:
sh.drop(sh[sh['关注人数']!=0].index)

              所在社区编号       交易时间  挂牌天数  关注人数      总价    平米均价     面积  卧室  客厅  厨房  浴室  楼层信息  建成时间                                               链家网址
id
逸成东01  1111027381533 2018-01-03     2     0   607.0   80729   75.2   2   1   1   1  中 22  2003  https://bj.lianjia.com/chengjiao/101102451242....
天通苑05  1111027380051 2018-01-03     2     0   372.0   41822   89.0   2   1   1   1   高 6  2001  https://bj.lianjia.com/chengjiao/101102452309....
汽南小01  1111027378900 2018-01-03     4     0   509.0  121191   42.0   1   1   1   1   顶 6  1985  https://bj.lianjia.com/chengjiao/101102446043....
门头沟01  1111052073923 2018-01-03     4     0   173.0   37495   46.1   1   1   1   1   顶 6  1990  https://bj.lianjia.com/chengjiao/101102446345....
新街口01  1111027380943 2018-01-03     4     0  1120.0  102970  108.8   3   1   1   2   中 6  2005  https://bj.lianjia.com/chengjiao/101102447671....
瑞祥里01  1111027379066 2018-01-03     5     0   277.0   41699   66.4   1   1   1   1   中 9  2006  https://bj.lianjia.com/chengjiao/101102445248....
和谐家01  1111027375384 2018-01-03     7     0   530.0   44419  119.3   3   1   1   1   底 6  2006  https://bj.lianjia.com/chengjiao/101102438759....
东辰小01  1111027376788 2018-01-03     7     0   190.0   20128   94.4   2   2   1   1   底 6  1998  https://bj.lianjia.com/chengjiao/101102439295....
一品嘉01  1111027381935 2018-01-03     9     0   219.0   24771   88.4   2   1   1   1   中 6  2012  https://bj.lianjia.com/chengjiao/101102434018....
天通苑03  1111027380043 2018-01-03    10     0   386.0   39615   97.4   2   1   1   2   中 6  2004  https://bj.lianjia.com/chengjiao/101102431831....
龙博苑02  1111027377721 2018-01-03    18     0   507.0   43124  117.6   3   1   1   2   中 6  2004  https://bj.lianjia.com/chengjiao/101102406817....
九和苑01  1111027377179 2018-01-03    26     0   760.0  102856   73.9   1   1   1   1  中 14  2005  https://bj.lianjia.com/chengjiao/101102383627....
高家园01  1111027374616 2018-01-03    27     0   339.0   60590   56.0   2   1   1   1   中 6  1986  https://bj.lianjia.com/chengjiao/101102378934....
蒲黄榆01  1111027378724 2018-01-03    67     0   222.0   60000   37.0   1   1   1   1  中 15  1991  https://bj.lianjia.com/chengjiao/101102244732....

In [56]:
sh.index[1:5]

Index(['天通苑05', '汽南小01', '门头沟01', '新街口01'], dtype='object', name='id')

In [57]:
sh['销售状态']=1
sh

              所在社区编号       交易时间  挂牌天数  关注人数      总价    平米均价     面积  卧室  客厅  厨房  浴室  楼层信息  建成时间                                               链家网址  销售状态
id
逸成东01  1111027381533 2018-01-03     2     0   607.0   80729   75.2   2   1   1   1  中 22  2003  https://bj.lianjia.com/chengjiao/101102451242....     1
天通苑05  1111027380051 2018-01-03     2     0   372.0   41822   89.0   2   1   1   1   高 6  2001  https://bj.lianjia.com/chengjiao/101102452309....     1
汽南小01  1111027378900 2018-01-03     4     0   509.0  121191   42.0   1   1   1   1   顶 6  1985  https://bj.lianjia.com/chengjiao/101102446043....     1
门头沟01  1111052073923 2018-01-03     4     0   173.0   37495   46.1   1   1   1   1   顶 6  1990  https://bj.lianjia.com/chengjiao/101102446345....     1
新街口01  1111027380943 2018-01-03     4     0  1120.0  102970  108.8   3   1   1   2   中 6  2005  https://bj.lianjia.com/chengjiao/101102447671....     1
...              ...        ...   ...   ...     ...     ...    ...  ..  ..  ..  ..   ...   ...                                                ...   ...
模式口01  1111027378400 2018-01-03   201     2   260.0   47247   55.0   2   1   1   1   中 6  1986  https://bj.lianjia.com/chengjiao/101101704540....     1
绿地新01  1111052857099 2018-01-03   208    38   305.0   34731   87.8   2   1   1   1  高 14  2012  https://bj.lianjia.com/chengjiao/101101685048....     1
兴隆家01  1111027381021 2018-01-03   229   100   515.0   49306  104.5   3   1   1   1  中 24  2001  https://bj.lianjia.com/chengjiao/101101601669....     1
融科香01  1111027379032 2018-01-03   231     9   507.0   36071  140.6   3   2   1   2   中 6  2009  https://bj.lianjia.com/chengjiao/101101594408....     1
龙博苑01  1111027377718 2018-01-03   259   226   380.0   47560   79.9   2   1   1   1   中 6  2004  https://bj.lianjia.com/chengjiao/101101492812....     1

[97 rows x 15 columns]

In [58]:
sh.loc['承泽苑01']=520
sh

              所在社区编号                 交易时间  挂牌天数  关注人数      总价    平米均价     面积   卧室   客厅   厨房   浴室  楼层信息  建成时间                                               链家网址  销售状态
id
逸成东01  1111027381533  2018-01-03 00:00:00     2     0   607.0   80729   75.2    2    1    1    1  中 22  2003  https://bj.lianjia.com/chengjiao/101102451242....     1
天通苑05  1111027380051  2018-01-03 00:00:00     2     0   372.0   41822   89.0    2    1    1    1   高 6  2001  https://bj.lianjia.com/chengjiao/101102452309....     1
汽南小01  1111027378900  2018-01-03 00:00:00     4     0   509.0  121191   42.0    1    1    1    1   顶 6  1985  https://bj.lianjia.com/chengjiao/101102446043....     1
门头沟01  1111052073923  2018-01-03 00:00:00     4     0   173.0   37495   46.1    1    1    1    1   顶 6  1990  https://bj.lianjia.com/chengjiao/101102446345....     1
新街口01  1111027380943  2018-01-03 00:00:00     4     0  1120.0  102970  108.8    3    1    1    2   中 6  2005  https://bj.lianjia.com/chengjiao/101102447671....     1
...              ...                  ...   ...   ...     ...     ...    ...  ...  ...  ...  ...   ...   ...                                                ...   ...
绿地新01  1111052857099  2018-01-03 00:00:00   208    38   305.0   34731   87.8    2    1    1    1  高 14  2012  https://bj.lianjia.com/chengjiao/101101685048....     1
兴隆家01  1111027381021  2018-01-03 00:00:00   229   100   515.0   49306  104.5    3    1    1    1  中 24  2001  https://bj.lianjia.com/chengjiao/101101601669....     1
融科香01  1111027379032  2018-01-03 00:00:00   231     9   507.0   36071  140.6    3    2    1    2   中 6  2009  https://bj.lianjia.com/chengjiao/101101594408....     1
龙博苑01  1111027377718  2018-01-03 00:00:00   259   226   380.0   47560   79.9    2    1    1    1   中 6  2004  https://bj.lianjia.com/chengjiao/101101492812....     1
承泽苑01            520                  520   520   520   520.0     520  520.0  520  520  520  520   520   520                                                520   520

[98 rows x 15 columns]

In [62]:

sh=sh.drop('单元',axis=1)
sh

              所在社区编号                 交易时间  挂牌天数  关注人数      总价    平米均价     面积   卧室   客厅   厨房   浴室  楼层信息  建成时间                                               链家网址  销售状态
id
逸成东01  1111027381533  2018-01-03 00:00:00     2     0   607.0   80729   75.2    2    1    1    1  中 22  2003  https://bj.lianjia.com/chengjiao/101102451242....     1
天通苑05  1111027380051  2018-01-03 00:00:00     2     0   372.0   41822   89.0    2    1    1    1   高 6  2001  https://bj.lianjia.com/chengjiao/101102452309....     1
汽南小01  1111027378900  2018-01-03 00:00:00     4     0   509.0  121191   42.0    1    1    1    1   顶 6  1985  https://bj.lianjia.com/chengjiao/101102446043....     1
门头沟01  1111052073923  2018-01-03 00:00:00     4     0   173.0   37495   46.1    1    1    1    1   顶 6  1990  https://bj.lianjia.com/chengjiao/101102446345....     1
新街口01  1111027380943  2018-01-03 00:00:00     4     0  1120.0  102970  108.8    3    1    1    2   中 6  2005  https://bj.lianjia.com/chengjiao/101102447671....     1
...              ...                  ...   ...   ...     ...     ...    ...  ...  ...  ...  ...   ...   ...                                                ...   ...
绿地新01  1111052857099  2018-01-03 00:00:00   208    38   305.0   34731   87.8    2    1    1    1  高 14  2012  https://bj.lianjia.com/chengjiao/101101685048....     1
兴隆家01  1111027381021  2018-01-03 00:00:00   229   100   515.0   49306  104.5    3    1    1    1  中 24  2001  https://bj.lianjia.com/chengjiao/101101601669....     1
融科香01  1111027379032  2018-01-03 00:00:00   231     9   507.0   36071  140.6    3    2    1    2   中 6  2009  https://bj.lianjia.com/chengjiao/101101594408....     1
龙博苑01  1111027377718  2018-01-03 00:00:00   259   226   380.0   47560   79.9    2    1    1    1   中 6  2004  https://bj.lianjia.com/chengjiao/101101492812....     1
承泽苑01            520                  520   520   520   520.0     520  520.0  520  520  520  520   520   520                                                520   520

[98 rows x 15 columns]

In [70]:
单元值=np.random.choice(['一单元','二单元','三单元'],sh.shape[0])
sh.insert(1,'单元',单元值)

In [71]:
sh

              所在社区编号   单元                 交易时间  挂牌天数  关注人数      总价    平米均价     面积   卧室   客厅   厨房   浴室  楼层信息  建成时间                                               链家网址  销售状态
id
逸成东01  1111027381533  二单元  2018-01-03 00:00:00     2     0   607.0   80729   75.2    2    1    1    1  中 22  2003  https://bj.lianjia.com/chengjiao/101102451242....     1
天通苑05  1111027380051  三单元  2018-01-03 00:00:00     2     0   372.0   41822   89.0    2    1    1    1   高 6  2001  https://bj.lianjia.com/chengjiao/101102452309....     1
汽南小01  1111027378900  三单元  2018-01-03 00:00:00     4     0   509.0  121191   42.0    1    1    1    1   顶 6  1985  https://bj.lianjia.com/chengjiao/101102446043....     1
门头沟01  1111052073923  二单元  2018-01-03 00:00:00     4     0   173.0   37495   46.1    1    1    1    1   顶 6  1990  https://bj.lianjia.com/chengjiao/101102446345....     1
新街口01  1111027380943  三单元  2018-01-03 00:00:00     4     0  1120.0  102970  108.8    3    1    1    2   中 6  2005  https://bj.lianjia.com/chengjiao/101102447671....     1
...              ...  ...                  ...   ...   ...     ...     ...    ...  ...  ...  ...  ...   ...   ...                                                ...   ...
绿地新01  1111052857099  一单元  2018-01-03 00:00:00   208    38   305.0   34731   87.8    2    1    1    1  高 14  2012  https://bj.lianjia.com/chengjiao/101101685048....     1
兴隆家01  1111027381021  二单元  2018-01-03 00:00:00   229   100   515.0   49306  104.5    3    1    1    1  中 24  2001  https://bj.lianjia.com/chengjiao/101101601669....     1
融科香01  1111027379032  二单元  2018-01-03 00:00:00   231     9   507.0   36071  140.6    3    2    1    2   中 6  2009  https://bj.lianjia.com/chengjiao/101101594408....     1
龙博苑01  1111027377718  三单元  2018-01-03 00:00:00   259   226   380.0   47560   79.9    2    1    1    1   中 6  2004  https://bj.lianjia.com/chengjiao/101101492812....     1
承泽苑01            520  二单元                  520   520   520   520.0     520  520.0  520  520  520  520   520   520                                                520   520

[98 rows x 16 columns]

In [75]:
sh

              所在社区编号   单元                 交易时间  挂牌天数  关注人数      总价    平米均价     面积   卧室   客厅   厨房   浴室  楼层信息  建成时间                                               链家网址  销售状态
id
逸成东01  1111027381533  二单元  2018-01-03 00:00:00     2     0   607.0   80729   75.2    2    1    1    1  中 22  2003  https://bj.lianjia.com/chengjiao/101102451242....     1
天通苑05  1111027380051  三单元  2018-01-03 00:00:00     2     0   372.0   41822   89.0    2    1    1    1   高 6  2001  https://bj.lianjia.com/chengjiao/101102452309....     1
汽南小01  1111027378900  三单元  2018-01-03 00:00:00     4     0   509.0  121191   42.0    1    1    1    1   顶 6  1985  https://bj.lianjia.com/chengjiao/101102446043....     1
门头沟01  1111052073923  二单元  2018-01-03 00:00:00     4     0   173.0   37495   46.1    1    1    1    1   顶 6  1990  https://bj.lianjia.com/chengjiao/101102446345....     1
新街口01  1111027380943  三单元  2018-01-03 00:00:00     4     0  1120.0  102970  108.8    3    1    1    2   中 6  2005  https://bj.lianjia.com/chengjiao/101102447671....     1
...              ...  ...                  ...   ...   ...     ...     ...    ...  ...  ...  ...  ...   ...   ...                                                ...   ...
绿地新01  1111052857099  一单元  2018-01-03 00:00:00   208    38   305.0   34731   87.8    2    1    1    1  高 14  2012  https://bj.lianjia.com/chengjiao/101101685048....     1
兴隆家01  1111027381021  二单元  2018-01-03 00:00:00   229   100   515.0   49306  104.5    3    1    1    1  中 24  2001  https://bj.lianjia.com/chengjiao/101101601669....     1
融科香01  1111027379032  二单元  2018-01-03 00:00:00   231     9   507.0   36071  140.6    3    2    1    2   中 6  2009  https://bj.lianjia.com/chengjiao/101101594408....     1
龙博苑01  1111027377718  三单元  2018-01-03 00:00:00   259   226   380.0   47560   79.9    2    1    1    1   中 6  2004  https://bj.lianjia.com/chengjiao/101101492812....     1
承泽苑01            520  二单元                  520   520   520   520.0     520  520.0  520  520  520  520   520   520                                                520   520

[98 rows x 16 columns]

In [78]:
sh2=sh.reindex(columns=['挂牌天数','交易时间','所在社区编号','销售状态'])
sh2['销售状态']=0
sh2

       挂牌天数                 交易时间         所在社区编号  销售状态
id
逸成东01     2  2018-01-03 00:00:00  1111027381533     0
天通苑05     2  2018-01-03 00:00:00  1111027380051     0
汽南小01     4  2018-01-03 00:00:00  1111027378900     0
门头沟01     4  2018-01-03 00:00:00  1111052073923     0
新街口01     4  2018-01-03 00:00:00  1111027380943     0
...     ...                  ...            ...   ...
绿地新01   208  2018-01-03 00:00:00  1111052857099     0
兴隆家01   229  2018-01-03 00:00:00  1111027381021     0
融科香01   231  2018-01-03 00:00:00  1111027379032     0
龙博苑01   259  2018-01-03 00:00:00  1111027377718     0
承泽苑01   520                  520            520     0

[98 rows x 4 columns]

In [80]:
sh4=sh.reindex(index=['新街口01','模式口01','霁月园01','逸成东01'])
sh4.loc['霁月园01']='-'
sh4

      所在社区编号   单元                 交易时间   挂牌天数 关注人数     总价   平米均价     面积 卧室 客厅 厨房 浴室  楼层信息   建成时间                                               链家网址 销售状态
id
新街口01  1e+12  三单元  2018-01-03 00:00:00      4    0  1e+03  1e+05  1e+02  3  1  1  2   中 6  2e+03  https://bj.lianjia.com/chengjiao/101102447671....    1
模式口01  1e+12  二单元  2018-01-03 00:00:00  2e+02    2  3e+02  5e+04  6e+01  2  1  1  1   中 6  2e+03  https://bj.lianjia.com/chengjiao/101101704540....    1
霁月园01      -    -                    -      -    -      -      -      -  -  -  -  -     -      -                                                  -    -
逸成东01  1e+12  二单元  2018-01-03 00:00:00      2    0  6e+02  8e+04  8e+01  2  1  1  1  中 22  2e+03  https://bj.lianjia.com/chengjiao/101102451242....    1

In [81]:
sh5=sh.reindex(index=['新街口01','模式口01','霁月园01','逸成东01'],fill_value='+++')
sh5

              所在社区编号   单元                 交易时间 挂牌天数 关注人数     总价    平米均价     面积   卧室   客厅   厨房   浴室  楼层信息  建成时间                                               链家网址 销售状态
id
新街口01  1111027380943  三单元  2018-01-03 00:00:00    4    0  1e+03  102970  1e+02    3    1    1    2   中 6  2005  https://bj.lianjia.com/chengjiao/101102447671....    1
模式口01  1111027378400  二单元  2018-01-03 00:00:00  201    2  3e+02   47247  6e+01    2    1    1    1   中 6  1986  https://bj.lianjia.com/chengjiao/101101704540....    1
霁月园01            +++  +++                  +++  +++  +++    +++     +++    +++  +++  +++  +++  +++   +++   +++                                                +++  +++
逸成东01  1111027381533  二单元  2018-01-03 00:00:00    2    0  6e+02   80729  8e+01    2    1    1    1  中 22  2003  https://bj.lianjia.com/chengjiao/101102451242....    1

In [82]:
sh

              所在社区编号   单元                 交易时间  挂牌天数  关注人数      总价    平米均价     面积   卧室   客厅   厨房   浴室  楼层信息  建成时间                                               链家网址  销售状态
id
逸成东01  1111027381533  二单元  2018-01-03 00:00:00     2     0   607.0   80729   75.2    2    1    1    1  中 22  2003  https://bj.lianjia.com/chengjiao/101102451242....     1
天通苑05  1111027380051  三单元  2018-01-03 00:00:00     2     0   372.0   41822   89.0    2    1    1    1   高 6  2001  https://bj.lianjia.com/chengjiao/101102452309....     1
汽南小01  1111027378900  三单元  2018-01-03 00:00:00     4     0   509.0  121191   42.0    1    1    1    1   顶 6  1985  https://bj.lianjia.com/chengjiao/101102446043....     1
门头沟01  1111052073923  二单元  2018-01-03 00:00:00     4     0   173.0   37495   46.1    1    1    1    1   顶 6  1990  https://bj.lianjia.com/chengjiao/101102446345....     1
新街口01  1111027380943  三单元  2018-01-03 00:00:00     4     0  1120.0  102970  108.8    3    1    1    2   中 6  2005  https://bj.lianjia.com/chengjiao/101102447671....     1
...              ...  ...                  ...   ...   ...     ...     ...    ...  ...  ...  ...  ...   ...   ...                                                ...   ...
绿地新01  1111052857099  一单元  2018-01-03 00:00:00   208    38   305.0   34731   87.8    2    1    1    1  高 14  2012  https://bj.lianjia.com/chengjiao/101101685048....     1
兴隆家01  1111027381021  二单元  2018-01-03 00:00:00   229   100   515.0   49306  104.5    3    1    1    1  中 24  2001  https://bj.lianjia.com/chengjiao/101101601669....     1
融科香01  1111027379032  二单元  2018-01-03 00:00:00   231     9   507.0   36071  140.6    3    2    1    2   中 6  2009  https://bj.lianjia.com/chengjiao/101101594408....     1
龙博苑01  1111027377718  三单元  2018-01-03 00:00:00   259   226   380.0   47560   79.9    2    1    1    1   中 6  2004  https://bj.lianjia.com/chengjiao/101101492812....     1
承泽苑01            520  二单元                  520   520   520   520.0     520  520.0  520  520  520  520   520   520                                                520   520

[98 rows x 16 columns]

In [2]:
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 10)
sh=pd.read_excel(r'C:\Users\YcAllenEffy\Desktop\消费指数.xlsx',sheet_name=[0,1],index_col=0)
df1=sh[0]
df2=sh[1]

In [3]:
df1

      总指数同比指数  服务类同比指数  总指数定基指数  服务类定基指数
年份
2003    101.5    102.6    108.1    149.9
2004    103.4    103.0    114.5    167.7
2005    100.8    101.9    118.0    175.2
2006    100.7    105.2    121.5    180.3
2007    100.0    101.9    124.1    186.6
2008    100.2    103.8    127.1    192.6
2009    100.4    102.6    130.3    203.2
2010     99.4    101.9    132.3    199.9
2011    100.8    103.5    136.3    205.7

In [4]:
df2

      总指数同比指数  食品类同比指数  总指数定基指数  食品类定基指数
年份
2007    104.1    108.6    109.2    113.3
2008    105.9    113.5    115.6    115.7
2009     98.7     98.5    114.1    115.1
2010    103.5    107.7    118.1    118.1
2011    105.4    111.9    124.5    121.6
2012    102.8    104.5    128.0    123.9
2013    102.7    102.9    131.5    130.3
2014    102.0    103.5    134.1    132.8
2015    102.2    103.2    137.1    137.8
2016    102.4    105.5    140.3    141.4

In [9]:
df1part=df1.loc[2003:2006,'总指数同比指数']

In [7]:
df2part=df2.loc[2007:2010,'总指数同比指数']

In [11]:
df1part.append(df2part)

年份
2003    101.5
2004    103.4
2005    100.8
2006    100.7
2007    104.1
2008    105.9
2009     98.7
2010    103.5
Name: 总指数同比指数, dtype: float64

In [13]:
pd.concat([df1,df2])

      总指数同比指数  服务类同比指数  总指数定基指数  服务类定基指数  食品类同比指数  食品类定基指数
年份
2003    101.5    102.6    108.1    149.9      NaN      NaN
2004    103.4    103.0    114.5    167.7      NaN      NaN
2005    100.8    101.9    118.0    175.2      NaN      NaN
2006    100.7    105.2    121.5    180.3      NaN      NaN
2007    100.0    101.9    124.1    186.6      NaN      NaN
...       ...      ...      ...      ...      ...      ...
2012    102.8      NaN    128.0      NaN    104.5    123.9
2013    102.7      NaN    131.5      NaN    102.9    130.3
2014    102.0      NaN    134.1      NaN    103.5    132.8
2015    102.2      NaN    137.1      NaN    103.2    137.8
2016    102.4      NaN    140.3      NaN    105.5    141.4

[19 rows x 6 columns]

In [14]:
a=pd.concat([df1,df2])
a.loc[2007]

      总指数同比指数  服务类同比指数  总指数定基指数  服务类定基指数  食品类同比指数  食品类定基指数
年份
2007    100.0    101.9    124.1    186.6      NaN      NaN
2007    104.1      NaN    109.2      NaN    108.6    113.3

In [15]:
pd.concat([df1,df2],ignore_index=True)

    总指数同比指数  服务类同比指数  总指数定基指数  服务类定基指数  食品类同比指数  食品类定基指数
0     101.5    102.6    108.1    149.9      NaN      NaN
1     103.4    103.0    114.5    167.7      NaN      NaN
2     100.8    101.9    118.0    175.2      NaN      NaN
3     100.7    105.2    121.5    180.3      NaN      NaN
4     100.0    101.9    124.1    186.6      NaN      NaN
..      ...      ...      ...      ...      ...      ...
14    102.8      NaN    128.0      NaN    104.5    123.9
15    102.7      NaN    131.5      NaN    102.9    130.3
16    102.0      NaN    134.1      NaN    103.5    132.8
17    102.2      NaN    137.1      NaN    103.2    137.8
18    102.4      NaN    140.3      NaN    105.5    141.4

[19 rows x 6 columns]

In [16]:
b=pd.concat([df1,df2],ignore_index=True)
b[['总指数同比指数','总指数定基指数']]

    总指数同比指数  总指数定基指数
0     101.5    108.1
1     103.4    114.5
2     100.8    118.0
3     100.7    121.5
4     100.0    124.1
..      ...      ...
14    102.8    128.0
15    102.7    131.5
16    102.0    134.1
17    102.2    137.1
18    102.4    140.3

[19 rows x 2 columns]

In [17]:
pd.concat([df1,df2],axis=1)

      总指数同比指数  服务类同比指数  总指数定基指数  服务类定基指数  总指数同比指数  食品类同比指数  总指数定基指数  食品类定基指数
年份
2003    101.5    102.6    108.1    149.9      NaN      NaN      NaN      NaN
2004    103.4    103.0    114.5    167.7      NaN      NaN      NaN      NaN
2005    100.8    101.9    118.0    175.2      NaN      NaN      NaN      NaN
2006    100.7    105.2    121.5    180.3      NaN      NaN      NaN      NaN
2007    100.0    101.9    124.1    186.6    104.1    108.6    109.2    113.3
...       ...      ...      ...      ...      ...      ...      ...      ...
2012      NaN      NaN      NaN      NaN    102.8    104.5    128.0    123.9
2013      NaN      NaN      NaN      NaN    102.7    102.9    131.5    130.3
2014      NaN      NaN      NaN      NaN    102.0    103.5    134.1    132.8
2015      NaN      NaN      NaN      NaN    102.2    103.2    137.1    137.8
2016      NaN      NaN      NaN      NaN    102.4    105.5    140.3    141.4

[14 rows x 8 columns]

In [19]:
c=pd.concat([df1,df2],axis=1)
c.iloc[::,[1,3,5,7]]

      服务类同比指数  服务类定基指数  食品类同比指数  食品类定基指数
年份
2003    102.6    149.9      NaN      NaN
2004    103.0    167.7      NaN      NaN
2005    101.9    175.2      NaN      NaN
2006    105.2    180.3      NaN      NaN
2007    101.9    186.6    108.6    113.3
...       ...      ...      ...      ...
2012      NaN      NaN    104.5    123.9
2013      NaN      NaN    102.9    130.3
2014      NaN      NaN    103.5    132.8
2015      NaN      NaN    103.2    137.8
2016      NaN      NaN    105.5    141.4

[14 rows x 4 columns]

In [24]:
d=pd.concat([df1,df2],axis=0)
d.loc[[2007,2009,2011],['总指数同比指数','总指数定基指数']]

      总指数同比指数  总指数定基指数
年份
2007    100.0    124.1
2007    104.1    109.2
2009    100.4    130.3
2009     98.7    114.1
2011    100.8    136.3
2011    105.4    124.5

In [25]:
e=pd.concat([df1,df2],axis=1,join='inner')
e

      总指数同比指数  服务类同比指数  总指数定基指数  服务类定基指数  总指数同比指数  食品类同比指数  总指数定基指数  食品类定基指数
年份
2007    100.0    101.9    124.1    186.6    104.1    108.6    109.2    113.3
2008    100.2    103.8    127.1    192.6    105.9    113.5    115.6    115.7
2009    100.4    102.6    130.3    203.2     98.7     98.5    114.1    115.1
2010     99.4    101.9    132.3    199.9    103.5    107.7    118.1    118.1
2011    100.8    103.5    136.3    205.7    105.4    111.9    124.5    121.6

In [27]:
f=pd.concat([df1,df2],axis=0,join='inner')
f

      总指数同比指数  总指数定基指数
年份
2003    101.5    108.1
2004    103.4    114.5
2005    100.8    118.0
2006    100.7    121.5
2007    100.0    124.1
...       ...      ...
2012    102.8    128.0
2013    102.7    131.5
2014    102.0    134.1
2015    102.2    137.1
2016    102.4    140.3

[19 rows x 2 columns]